name: 'Setup php'
description: 'Setup php'
runs:
  using: "composite"
  steps:
    - name: PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "8.3"
        coverage: none

    - uses: "ramsey/composer-install@v3"
