@startuml
title ページの取得
User -> ScrapeCommand: scrape:site {--sitename}
ScrapeCommand -> SiteServiceFactory: make(sitename)
ScrapeCommand <-- SiteServiceFactory: FooSiteService
ScrapeCommand -> FooSiteService: getUrls
ScrapeCommand <-- FooSiteService: urls
ScrapeCommand -> FooSiteService: getHTML(url)
ScrapeCommand <-- FooSiteService: html
ScrapeCommand -> FooSiteService: saveOrUpdateRawPage(url, html)
FooSiteService -> RawPage: updateOrCreate
ScrapeCommand <-- RawPage: raw_page
ScrapeCommand -> FooSiteService: removeExcludes(urls)
FooSiteService -> RawPage: delete
ScrapeCommand <-- RawPage: result
User <- ScrapeCommand: show result
@enduml
@startuml
title ページテキストの抽出
User -> ExtractCommand: extract:pages
ExtractCommand -> SiteServiceFactory: make(sitename)
ExtractCommand <-- SiteServiceFactory: FooSiteService
ExtractCommand -> FooSiteService: getUpdatedRawPages
FooSiteService -> RawPage: get
ExtractCommand <-- RawPage: raw_pages
ExtractCommand -> FooSiteService: extractContents
ExtractCommand <-- FooSiteService: [title, text, paks]
ExtractCommand -> FooSiteService: saveOrUpdatePage
FooSiteService -> Page: updateOrCreate
ExtractCommand <-- Page: page
User <- ExtractCommand: show result
@enduml
