name: auto package update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  auto-package-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          # Must be used to trigger workflow after push
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy .env
        run: php -r "copy('.env.ci', '.env');"

      - uses: ./.github/actions/php
      - uses: ./.github/actions/nodejs

      - name: Run composer update
        run: composer update && composer bump && composer update

      - name: Run npm update
        run: npm update

      - # commit only to core contributors who have repository access
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[ci] package-updates"
          commit_author: "GitHub Action <actions@github.com>"
          commit_user_email: "action@github.com"
