name: auto package update

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Copy .env
        run: php -r "copy('.env.ci', '.env');"
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
      - name: Run composer update
        run: composer update && composer bump && composer update

      - name: Setup Node
        uses: actions/setup-node@v3
      - name: npm ci
        run: npm update

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply update
          push_options: "--force"
