# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [master]
    tags: ["**"]
  pull_request:
    branches: [master, develop]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: .env
        run: php -r "copy('.env.ci', '.env');"

      - name: Cache build assets
        id: cache-assets
        uses: actions/cache@v2
        env:
          cache-name: cache-assets
        with:
          path: ./public
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Setup Node
        if: steps.cache-assets.outputs.cache-hit != 'true'
        uses: actions/setup-node@v2
      - name: npm ci
        if: steps.cache-assets.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Assets
        if: steps.cache-assets.outputs.cache-hit != 'true'
        run: npm run prod

      - name: PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8"
      - name: PHP vendor Cache
        id: cache-vendor
        uses: actions/cache@v2
        with:
          path: ./vendor
          key: ${{ runner.os }}-cache-vendor-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-vendor-
      - name: Composer Install
        if: steps.cache-vendor.outputs.cache-hit != 'true'
        run: composer install
      - name: Start MySQL
        run: sudo /etc/init.d/mysql start
      - name: Setup database
        run: mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test'
      - name: Test
        run: php artisan test -v --env=local

      - if: failure()
        name: Display Error Log
        run: "[ -e storage/logs/laravel.log ] && cat storage/logs/laravel.log || echo 'no log file.'"

  deploy:
    # tag push -> テスト通過後デプロイ
    needs: test
    if: ${{ success() && startsWith( github.ref, 'refs/tags/' ) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: .env
        run: php -r "copy('.env.deploy', '.env');"

      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: npm ci
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build Assets
        run: npm run prod

      - name: Install SSH key
        run: mkdir -p ~/.ssh \
          && echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa \
          && chmod 0600 ~/.ssh/id_rsa \
          && echo "${{secrets.KNOWN_HOSTS}}" >> ~/.ssh/known_hosts
      - name: Deploy
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: cd ${{ secrets.APP_DIR }}
            && git fetch -p
            && git checkout ${{ env.github.ref }}
            && git pull
            && bash -c 'sed -i "" "s/APP_VERSION=.*/APP_VERSION=$( git describe )/" .env'
            && composer install --optimize-autoloader --no-dev
            && php artisan migrate --force
            && php artisan migrate:status
            && php artisan optimize
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          privateKey: /home/runner/.ssh/id_rsa

      - name: rsync public dir
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -ahvzr --delete --exclude 'storage'
          RSYNC_TARGET: ${{ secrets.APP_DIR }}/public
          RSYNC_SOURCE: /public/
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_KEY}}
          SSH_USERNAME: ${{secrets.USER}}
          SSH_HOSTNAME: ${{secrets.HOST}}
